#!/usr/bin/env python3
"""
Generate kotlin-coroutines-skill/references/ref-*.md from BEST_PRACTICES + rule-codes.yml.

Usage (from repo root):
  python3 kotlin-coroutines-skill/scripts/generate_refs.py
  python3 kotlin-coroutines-skill/scripts/generate_refs.py --check
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any


def load_yaml(path: Path) -> Any:
    """Load YAML via PyYAML, or Ruby psych on macOS/Linux when PyYAML is absent."""
    try:
        import yaml  # type: ignore

        with path.open(encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    except ImportError:
        pass
    try:
        result = subprocess.run(
            [
                "ruby",
                "-ryaml",
                "-rjson",
                "-e",
                "puts JSON.generate(YAML.load_file(ARGV[0]))",
                str(path),
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        return json.loads(result.stdout) or {}
    except (FileNotFoundError, subprocess.CalledProcessError, json.JSONDecodeError) as exc:
        print(
            "Cannot load YAML. Install PyYAML (`pip install pyyaml`) or Ruby with psych.\n"
            f"Failed reading {path}: {exc}",
            file=sys.stderr,
        )
        sys.exit(1)

SKILL_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = SKILL_DIR.parent
BEST_PRACTICES = REPO_ROOT / "docs" / "BEST_PRACTICES_COROUTINES.md"
RULE_CODES = REPO_ROOT / "docs" / "rule-codes.yml"
MANIFEST = SKILL_DIR / "ref-manifest.yml"
EXAMPLES = SKILL_DIR / "ref-examples.yml"
REFS_DIR = SKILL_DIR / "references"

GENERATED_BANNER = (
    "<!-- Generated by kotlin-coroutines-skill/scripts/generate_refs.py. "
    "Edit ref-examples.yml or BEST_PRACTICES, then re-run the script. -->\n\n"
)

HEADER_RE = re.compile(
    r"^###\s+(\d+\.\d+)\s+([A-Z][A-Z0-9_]+)\s+—\s+(.+)$",
    re.MULTILINE,
)
TABLE_BAD_RE = re.compile(r"\|\s*\*\*Bad Practice\*\*\s*\|\s*([^|]+?)\s*\|", re.DOTALL)
TABLE_REC_RE = re.compile(r"\|\s*\*\*Recommended\*\*\s*\|\s*([^|]+?)\s*\|", re.DOTALL)
KOTLIN_BLOCK_RE = re.compile(r"```kotlin\n(.*?)```", re.DOTALL)

GOOD_SPLIT_MARKERS = re.compile(
    r"^//\s*(GOOD|Parallel|Lifecycle-aware|catch before|Option A|runTest|Backing property|"
    r"callbackFlow with|suspendCancellableCoroutine|GOOD alternative)",
    re.MULTILINE | re.IGNORECASE,
)


def parse_best_practices(text: str) -> dict[str, dict]:
    """Split BEST_PRACTICES into sections keyed by rule code (e.g. INTEROP_004)."""
    sections: dict[str, dict] = {}
    parts = re.split(r"(?=^###\s+\d)", text, flags=re.MULTILINE)
    for part in parts:
        m = HEADER_RE.search(part)
        if not m:
            continue
        section_num, code, title = m.group(1), m.group(2), m.group(3).strip()
        body = part[m.end() :]
        bad = TABLE_BAD_RE.search(body)
        rec = TABLE_REC_RE.search(body)
        kotlin_blocks = KOTLIN_BLOCK_RE.findall(body)
        sections[code] = {
            "section": section_num,
            "title": title,
            "bad_practice": clean_cell(bad.group(1)) if bad else "",
            "recommended": clean_cell(rec.group(1)) if rec else "",
            "kotlin_blocks": [b.strip() for b in kotlin_blocks],
        }
    return sections


def clean_cell(text: str) -> str:
    return re.sub(r"\s+", " ", text.strip())


def split_kotlin_block(block: str) -> tuple[str | None, str | None]:
    """Split a combined kotlin block into bad and good parts."""
    match = GOOD_SPLIT_MARKERS.search(block)
    if match:
        bad = block[: match.start()].strip()
        good = block[match.start() :].strip()
        return bad or None, good or None
    return block.strip() or None, None


def extract_examples_from_section(blocks: list[str]) -> tuple[str | None, str | None]:
    if not blocks:
        return None, None
    if len(blocks) >= 2:
        bad = blocks[0].strip()
        good = blocks[1].strip()
        if not bad.lower().startswith("// bad"):
            bad = f"// BAD\n{bad}"
        if not good.lower().startswith("// good"):
            good = f"// GOOD\n{good}"
        return bad, good
    return split_kotlin_block(blocks[0])


def format_kotlin(code: str | None) -> str:
    if not code:
        return ""
    code = code.strip()
    if not code.startswith("```"):
        return f"\n```kotlin\n{code}\n```\n"
    return f"\n{code}\n"


def build_toolkit(rule_meta: dict) -> str:
    code = rule_meta.get("code", "")
    lines = [f"- **Rule code:** `{code}`"]

    tool_parts: list[str] = []
    for key, label in [
        ("compiler", "Compiler"),
        ("detekt", "Detekt"),
        ("lint", "Lint"),
        ("intellij", "IntelliJ"),
    ]:
        names = rule_meta.get(key) or []
        if names:
            tool_parts.append(f"{label} `{', '.join(names)}`")
    if tool_parts:
        lines.append(f"- **Tools:** {', '.join(tool_parts)}")

    detekt_names = rule_meta.get("detekt") or []
    intellij_names = rule_meta.get("intellij") or []
    suppress_names = sorted(set(detekt_names + intellij_names))
    if suppress_names:
        suppress = ", ".join(f'`@Suppress("{n}")`' for n in suppress_names)
        lines.append(f"- **Suppress:** {suppress}")

    notes = rule_meta.get("notes")
    if notes:
        lines.append(f"- **Note:** {notes}")

    severity = rule_meta.get("default_severity")
    if severity:
        lines.append(f"- **Default severity:** {severity}")

    return "\n".join(lines)


def build_why(
    bad_text: str,
    recommended_text: str,
    overlay: dict | None,
) -> str:
    if overlay and overlay.get("why"):
        return overlay["why"].strip()
    if bad_text and recommended_text:
        return (
            f"The bad pattern ({bad_text[:120]}…) risks incorrect concurrency behavior. "
            f"Instead: {recommended_text[:200]}."
        )
    return bad_text or recommended_text or "See Bad Practice and Recommended above."


def build_quick_fix(
    overlay: dict | None,
    bad_code: str | None,
    good_code: str | None,
) -> str:
    if overlay and overlay.get("quick_fix"):
        q = overlay["quick_fix"]
        err = q.get("erroneous", "…")
        opt = q.get("optimized", "…")
        return f"| {err} | {opt} |"
    if bad_code and good_code:
        bad_line = _meaningful_line(bad_code)
        good_line = _meaningful_line(good_code)
        if bad_line and good_line:
            return f"| `{bad_line}` | `{good_line}` |"
    return "| See examples above | Apply Recommended pattern |"


def _meaningful_line(code: str) -> str:
    """Pick a representative one-liner for the quick-fix table."""
    for line in code.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue
        if stripped in ("}", "{"):
            continue
        return stripped[:100]
    return ""


def generate_ref(
    entry: dict,
    bp_sections: dict[str, dict],
    rules_by_code: dict[str, dict],
    examples: dict,
) -> str:
    rule_code = entry["rule"]
    file_name = entry["file"]
    bp = bp_sections.get(rule_code)
    rule_meta = rules_by_code.get(rule_code, {"code": rule_code})
    overlay = examples.get(rule_code, {})

    if not bp:
        print(f"WARN: no BEST_PRACTICES section for {rule_code} ({file_name})", file=sys.stderr)

    section = bp["section"] if bp else rule_meta.get("section", "?")
    title = bp["title"] if bp else rule_meta.get("title", rule_code)
    bad_practice = bp["bad_practice"] if bp else ""
    recommended = bp["recommended"] if bp else ""

    bad_code, good_code = extract_examples_from_section(bp["kotlin_blocks"] if bp else [])
    if overlay.get("bad"):
        if not bad_code:
            bad_code = overlay["bad"].strip()
    if overlay.get("good"):
        if not good_code:
            good_code = overlay["good"].strip()

    if bad_code and not bad_code.lstrip().startswith("//"):
        bad_code = f"// BAD\n{bad_code}"
    if good_code and not good_code.lstrip().startswith("//"):
        good_code = f"// GOOD\n{good_code}"

    why = build_why(bad_practice, recommended, overlay)
    quick_row = build_quick_fix(overlay, bad_code, good_code)
    toolkit = build_toolkit(rule_meta)

    lines = [
        GENERATED_BANNER.rstrip(),
        f"# {section} {title} ({rule_code})",
        "",
        "## Bad Practice",
        "",
        bad_practice or "_See kotlin example below._",
    ]
    if bad_code:
        lines.append(format_kotlin(bad_code).rstrip())

    lines.extend(["", "## Recommended", "", recommended or "_See kotlin example below._"])
    if good_code:
        lines.append(format_kotlin(good_code).rstrip())

    lines.extend(
        [
            "",
            "## Why",
            "",
            why,
            "",
            "## Quick fix",
            "",
            "| Erroneous | Optimized |",
            "|-----------|-----------|",
            quick_row,
            "",
            "## Toolkit (Structured Coroutines)",
            "",
            toolkit,
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate skill reference markdown files.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if any generated file would change.",
    )
    args = parser.parse_args()

    for path in (BEST_PRACTICES, RULE_CODES, MANIFEST):
        if not path.is_file():
            print(f"Missing required file: {path}", file=sys.stderr)
            return 1

    bp_text = BEST_PRACTICES.read_text(encoding="utf-8")
    bp_sections = parse_best_practices(bp_text)
    rules_doc = load_yaml(RULE_CODES)
    rules_by_code = {r["code"]: r for r in rules_doc.get("rules", [])}
    manifest = load_yaml(MANIFEST)
    examples = load_yaml(EXAMPLES) if EXAMPLES.is_file() else {}

    stale: list[str] = []
    for entry in manifest.get("refs", []):
        out_path = REFS_DIR / entry["file"]
        content = generate_ref(entry, bp_sections, rules_by_code, examples)
        if args.check:
            existing = out_path.read_text(encoding="utf-8") if out_path.is_file() else ""
            if existing != content:
                stale.append(entry["file"])
        else:
            out_path.write_text(content, encoding="utf-8")
            print(f"Wrote {out_path.relative_to(REPO_ROOT)}")

    if args.check:
        if stale:
            print("Out of date skill refs:", ", ".join(stale), file=sys.stderr)
            return 1
        print("All skill refs up to date.")
        return 0

    print(f"Generated {len(manifest.get('refs', []))} reference(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
